# Generated by Django 4.2.7 on 2024-03-06 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking_lot', '0002_parkinglot_iban_parkinglot_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkinglot',
            name='phone_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
