# Generated by Django 4.2.7 on 2024-03-08 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking_lot', '0003_alter_parkinglot_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkinglot',
            name='street_address',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
