# Generated by Django 4.2.7 on 2024-04-15 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0001_initial'),
        ('parking_lot', '0004_alter_parkinglot_street_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkinglot',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='city.city'),
        ),
    ]
