# Generated by Django 4.2.7 on 2024-05-22 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('image_task', '0001_initial'),
        ('spot_detection', '0002_boundingbox_parking_spot_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boundingbox',
            name='task_id',
        ),
        migrations.AddField(
            model_name='boundingbox',
            name='image_task',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='image_task.imagetask'),
        ),
        migrations.AddField(
            model_name='boundingbox',
            name='is_drawn',
            field=models.BooleanField(default=False),
        ),
    ]
