from django.urls import path
from .views import (ParkingLotListCreateView,
    ParkingLotRetrieveUpdateDestroyView,
    ParkingLotAddViewSet,
    UserParkingLotsView,
    TestParkingLotAddView,
    UserStreetAddressListView,
    ParkingLotByCityView,
    UserParkingLotDataView,
    ParkingLotEditPrice,
    ParkingLotEditPhone,
    ParkingLotEditTimes,
    ParkingLotEditCapacity,
    ParkingLotEditAddress,
    OpenParkingLotsView)

urlpatterns = [
    path('parking-lot/', ParkingLotListCreateView.as_view(), name='parking-lots-list-create'),
    path('user/street-address/', UserStreetAddressListView.as_view(), name='user-street-address-list'),
    path('test-parking-lot/', TestParkingLotAddView.as_view(), name='parking-lots-list-create'),
    path('parking-lot/<int:id>/', ParkingLotRetrieveUpdateDestroyView.as_view(), name='parking-lot-detail'),
    path('user-parking/', ParkingLotAddViewSet.as_view(), name='parking-lot-detail'),
    path('user-parking-lots/', UserParkingLotsView.as_view(), name='parking-lot-detail'),
    path('parking-lots/by-city/', ParkingLotByCityView.as_view(), name='parking-lots-by-city'),
    path('lot-details/', UserParkingLotDataView.as_view(), name='parking-lot-details'),
    path('price-update/', ParkingLotEditPrice.as_view(), name='price-update'),
    path('phone-update/', ParkingLotEditPhone.as_view(), name='phone-update'),
    path('times-update/', ParkingLotEditTimes.as_view(), name='times-update'),
    path('capacity-update/', ParkingLotEditCapacity.as_view(), name='capacity-update'),
    path('address-update/', ParkingLotEditAddress.as_view(), name='address-update'),
    path('radius-search/', OpenParkingLotsView.as_view(), name='radius-search'),
]