# Generated by Django 4.2.7 on 2023-12-26 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_markers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marker',
            old_name='created_at',
            new_name='timestamp',
        ),
        migrations.RemoveField(
            model_name='marker',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='marker',
            name='subscriber',
        ),
        migrations.AddField(
            model_name='marker',
            name='latitude',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='marker',
            name='longitude',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
