# Generated by Django 4.2.7 on 2023-12-26 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_markers', '0003_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='marker',
            name='is_subscribed',
            field=models.BooleanField(default=False),
        ),
    ]
