# Generated by Django 4.2.7 on 2024-05-22 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parking_lot', '0007_alter_parkinglot_latitude_alter_parkinglot_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingSpot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField()),
                ('sector', models.CharField(max_length=5)),
                ('number', models.IntegerField()),
                ('is_occupied', models.BooleanField()),
                ('parking_lot', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='parking_lot.parkinglot')),
            ],
        ),
    ]
