# Generated by Django 4.2.7 on 2024-05-22 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('image_task', '0001_initial'),
        ('parking_spot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingspot',
            name='image_task',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='image_task.imagetask'),
        ),
    ]
