# Generated by Django 4.2.7 on 2024-05-22 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('image_task', '0001_initial'),
        ('parking_spot', '0002_parkingspot_image_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingspot',
            name='image_task',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='image_task.imagetask'),
        ),
    ]
