# Generated by Django 4.2.7 on 2023-12-02 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sql_authentication', '0002_userprofile_delete_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='email',
            new_name='username',
        ),
    ]
