# Generated by Django 4.2.7 on 2023-12-02 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sql_authentication', '0003_rename_email_userprofile_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
