# Generated by Django 4.2.7 on 2024-05-23 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagetask',
            name='camera_type',
            field=models.CharField(choices=[('connectedCamera', 'Connected Camera'), ('remoteIP', 'Remote IP Address'), ('liveStream', 'Live Stream'), ('localVideo', 'Local Video')], default=None, max_length=50, null=True),
        ),
    ]
