# Generated by Django 4.2.7 on 2024-05-24 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_task', '0002_imagetask_camera_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagetask',
            name='device_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='imagetask',
            name='label',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
