# Generated by Django 4.1.13 on 2024-05-26 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_task', '0003_imagetask_device_id_imagetask_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagetask',
            name='destination_type',
            field=models.CharField(choices=[('spot', 'Spot'), ('entrance', 'Entrance'), ('exit', 'Exit')], default=None, max_length=50, null=True),
        ),
    ]
