# Generated by Django 4.1.13 on 2024-05-26 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_task', '0004_imagetask_destination_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagetask',
            name='destination_type',
            field=models.CharField(choices=[('spot', 'Spot'), ('entrance', 'Entrance'), ('exit', 'Exit')], default='spot', max_length=50, null=True),
        ),
    ]
