# Generated by Django 4.2.7 on 2024-05-19 18:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parking_lot', '0007_alter_parkinglot_latitude_alter_parkinglot_longitude'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('hourly_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('spot_description', models.CharField(max_length=255)),
                ('time_spent', models.PositiveIntegerField(default=0)),
                ('is_paid', models.BooleanField(default=False)),
                ('final_cost', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('license_plate', models.CharField(default='', max_length=255)),
                ('reserved_time', models.BooleanField(default=False)),
                ('parking_lot', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='parking_lot.parkinglot')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
