# Generated by Django 4.2.7 on 2024-02-11 10:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.PositiveIntegerField()),
                ('parking_lot_id', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('hourly_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('spot_description', models.CharField(max_length=255)),
                ('time_spent', models.PositiveIntegerField()),
                ('is_paid', models.BooleanField(default=False)),
                ('final_cost', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
    ]
