# Generated by Django 4.2.7 on 2024-02-11 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking_invoice', '0002_alter_parkinginvoice_parking_lot_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkinginvoice',
            name='final_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='parkinginvoice',
            name='time_spent',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
