# Generated by Django 4.2.7 on 2024-04-13 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking_invoice', '0003_alter_parkinginvoice_final_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkinginvoice',
            name='license_plate',
            field=models.CharField(default='', max_length=255),
        ),
    ]
