# Generated by Django 4.2.7 on 2024-04-13 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking_invoice', '0004_parkinginvoice_license_plate'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkinginvoice',
            name='reserved_time',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
