# Generated by Django 4.2.7 on 2024-04-16 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking_invoice', '0005_parkinginvoice_reserved_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkinginvoice',
            name='reserved_time',
            field=models.BooleanField(default=False),
        ),
    ]
