# Generated by Django 4.2.7 on 2024-05-14 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parking_lot', '0007_alter_parkinglot_latitude_alter_parkinglot_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingLotTile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=50)),
                ('tile_type', models.CharField(max_length=50)),
                ('rotation', models.IntegerField(default=0)),
                ('sector', models.CharField(blank=True, max_length=10, null=True)),
                ('number', models.PositiveIntegerField(blank=True, null=True)),
                ('parking_lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking_lot.parkinglot')),
            ],
        ),
    ]
