# Generated by Django 4.2.7 on 2024-01-20 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_blacklistedtoken'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
