# Generated by Django 4.2.7 on 2024-05-19 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_article_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='read_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='article',
            name='topic',
            field=models.CharField(blank=True, choices=[('sports', 'Sports'), ('announcements', 'Announcements'), ('emergency', 'Emergency'), ('city', 'City'), ('green', 'Green')], max_length=20, null=True),
        ),
    ]
