# Generated by Django 4.2.7 on 2024-05-13 14:14

from django.db import migrations, models
import django.db.models.deletion
import ocupancy_metrics.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parking_lot', '0006_parkinglot_latitude_parkinglot_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='OccupancyMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_current_occupancy', models.PositiveIntegerField(default=0)),
                ('current_occupancy', models.JSONField(default=ocupancy_metrics.models.default_week_structure)),
                ('average_occupancy', models.JSONField(default=ocupancy_metrics.models.default_week_structure)),
                ('last_update', models.DateField(auto_now=True)),
                ('parking_lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking_lot.parkinglot')),
            ],
        ),
    ]
