# Generated by Django 4.2.7 on 2024-01-25 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parking_lot', '0001_initial'),
        ('entrance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingEntrance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entrance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entrance.entrance')),
                ('parking_lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking_lot.parkinglot')),
            ],
        ),
    ]
