# Generated by Django 4.2.7 on 2024-05-14 07:47

from django.db import migrations, models
import django.db.models.deletion
import income_metrics.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parking_lot', '0006_parkinglot_latitude_parkinglot_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomeMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_current', models.JSONField(default=income_metrics.models.default_daily_income)),
                ('daily_average', models.JSONField(default=income_metrics.models.default_daily_income)),
                ('monthly_total', models.JSONField(default=income_metrics.models.default_monthly_income)),
                ('yearly_total', models.JSONField(default=dict)),
                ('last_update', models.DateField(auto_now=True)),
                ('parking_lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking_lot.parkinglot')),
            ],
        ),
    ]
