# Generated by Django 4.1.13 on 2024-06-12 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income_metrics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomemetrics',
            name='total_current_income',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
